vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set smartindent")
vim.cmd("set mouse=a")
vim.cmd("set shiftwidth=4")
vim.cmd("set tabstop=4")
vim.cmd("set scrolloff=10")
vim.cmd("set expandtab")
vim.cmd("set clipboard+=unnamedplus")
vim.opt.clipboard = 'unnamedplus'
